const fs = require('fs');
const path = require('path');
const { root, sha256, normalizeText, request, delay, writeIfChanged } = require('./core');
const { runClasp, run: deploy } = require('../../src/manage_deploy');
function configuration() {
    const file = path.join(root, '.env');
    const settings = { ...process.env };
    if (fs.existsSync(file)) {
        for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
            const match = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$/);
            if (match) settings[match[1]] = match[2].replace(/^(['"])(.*)\1$/, '$2');
        }
    }
    if (!/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(settings.GAS_DEPLOY_URL || '')) throw new Error('固定 GAS_DEPLOY_URL が必要です。');
    if (!settings.GAS_SECRET_TOKEN) throw new Error('GAS_SECRET_TOKEN が必要です。');
    return settings;
}
function fingerprint() {
    const excluded = new Set(['manage_deploy.js', 'update_env.js', 'sync_build.js']);
    const files = fs.readdirSync(path.join(root, 'src')).filter(name => !excluded.has(name) && /\.(js|html|json)$/.test(name)).sort();
    return sha256(files.map(name => name + '\n' + normalizeText(fs.readFileSync(path.join(root, 'src', name), 'utf8'))).join('\n'));
}
function prepareBuild() {
    writeIfChanged('src/sync_build.js', `// Generated by sync-data.\nconst SYNC_SOURCE_HASH = '${fingerprint()}';\n`);
}
async function call(settings, action, extra = {}) {
    const response = await request(settings.GAS_DEPLOY_URL, {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, timeout: 360000,
        body: JSON.stringify({ action, token: settings.GAS_SECRET_TOKEN, ...extra })
    });
    const result = await response.json();
    if (result.status !== 'success') throw new Error(`GAS ${action}: ${result.error || result.message || result.status}`);
    return result;
}
async function exportSnapshot(settings, requestId) {
    let error;
    for (const ms of [0, 3000, 10000]) {
        await delay(ms);
        try { return await call(settings, 'exportSnapshot', { requestId }); }
        catch (e) { error = e; if (/validation|必須|列|空|欠落/i.test(e.message)) throw e; }
    }
    throw error;
}
async function inspect(settings) {
    try { return await call(settings, 'syncInfo'); }
    catch (error) {
        if (/Unknown action/.test(error.message)) return null;
        throw error;
    }
}
async function ensureDeployment(settings, state, save) {
    const hash = fingerprint();
    const observed = await inspect(settings);
    if (observed && observed.sourceHash === hash) { state.gasHash = hash; save(); return hash; }
    if (state.gasApproval !== hash) throw new Error('GAS の更新前確認が必要です。sync-data を再実行してください。');
    console.log('GAS ソースを更新し、固定デプロイを検証します。');
    runClasp(['push', '-f']);
    deploy();
    let verified = null;
    for (const waitMs of [0, 2000, 5000, 10000, 20000]) {
        await delay(waitMs);
        verified = await call(settings, 'syncInfo');
        if (verified.sourceHash === hash) break;
    }
    if (!verified || verified.sourceHash !== hash) throw new Error('デプロイした GAS ソースの内容を確認できません。');
    state.gasHash = hash;
    save();
    return hash;
}
module.exports = { configuration, fingerprint, prepareBuild, inspect, call, exportSnapshot, ensureDeployment };
