const fs = require('fs');
const path = require('path');
const { root, sha256, normalizeText, writeIfChanged } = require('./sync/core');
function build() {
    const sources = JSON.parse(fs.readFileSync(path.join(root, 'frontend/bundle.json'), 'utf8'));
    const bundle = '// Generated by scripts/build-site.js. Edit frontend/ or src/search_core.js.\n' + sources.map(file =>
        `\n// ---- ${file} ----\n` + normalizeText(fs.readFileSync(path.join(root, file), 'utf8'))).join('\n');
    writeIfChanged('mahler-search-app/js/app.js', bundle);
    writeIfChanged('mahler-search-app/js/score_metadata.js', fs.readFileSync(path.join(root, 'src/score_metadata.js'), 'utf8'));
    const versions = {};
    for (const dir of ['js', 'css']) {
        for (const name of fs.readdirSync(path.join(root, 'mahler-search-app', dir))) {
            if (!/\.(js|css)$/.test(name)) continue;
            const relative = `${dir}/${name}`;
            versions[relative] = sha256(normalizeText(fs.readFileSync(path.join(root, 'mahler-search-app', relative), 'utf8'))).slice(0, 12);
        }
    }
    const pages = ['index.html', 'privacy.html', 'license.html', ...fs.readdirSync(path.join(root, 'mahler-search-app'))
        .filter(name => name.endsWith('.html') && name !== 'dic.html' && !name.endsWith('_test.html')).map(name => 'mahler-search-app/' + name)];
    for (const page of pages) {
        const html = fs.readFileSync(path.join(root, page), 'utf8');
        writeIfChanged(page, html.replace(/((?:src|href)=["'])(?:mahler-search-app\/)?((?:js|css)\/[^"'?]+)(?:\?v=[^"']*)?(["'])/g,
            (match, before, asset, quote) => versions[asset] ? `${before}${page.startsWith('mahler-search-app/') ? '' : 'mahler-search-app/'}${asset}?v=${versions[asset]}${quote}` : match));
    }
    // The dictionary is rendered in GAS; its generator receives the same asset hashes.
    writeIfChanged('src/asset_versions.js', `// Generated by scripts/build-site.js.\nconst PUBLIC_ASSET_VERSIONS = ${JSON.stringify(versions)};\n`);
    return versions;
}
if (require.main === module) build();
module.exports = { build };
