// Generated by scripts/build-site.js.
const PUBLIC_ASSET_VERSIONS = {"js/analytics.js":"384b45d7de22","js/app.js":"5d5ebb282ac0","js/score_metadata.js":"f0faf2281480","js/wagner_strauss.js":"8cb4cf33e0c1","css/common.css":"c78b63196a8d","css/common_terms.css":"6d603a4a9278","css/style.css":"ac6043a75b68"};
